<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Your first page!</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">

	<link rel="stylesheet" href="<?= Url::cdn('css/main.css') ?>">
</head>
<body>

	<h1>Welcome</h1>
	<hr/>
	<p>
		<?= $this->text ?>
	</p>

	<script type="text/javascript" src="<?= Url::cdn('js/main.js') ?>"></script>
</body>
</html>
