<div class="jumbotron">
	<h1>Welcome to your new site!</h1>
	<p>
		If you see this message, it means you're successfully running your project
		with <a href="http://koldy.net" target="_blank">Koldy PHP Framework</a>!
	</p>
	<p>
		But, this page will be shown with minimal configuration. If you want to
		be sure that everything is configured good, then please click on the
		links in the menu to see what else you should do.
	</p>
</div>